version: "3"
services:
    mysql:
        container_name: crudjdbc
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: mysql
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: 654321
        ports:
            - 3306:3306
        ##1
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - default

##2
volumes:
    mysql-data:
          name: crudjdbc-data


